// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ChatResponse struct {
	Content string `json:"content"`
	IsLast  bool   `json:"isLast"`
}

type InterviewAPPChatReq struct {
	Message string `form:"message"`
	ChatId  string `form:"chatId"`
}
