// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"ai-gozero-agent/api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Go面试官聊天SSE流式接口
				Method:  http.MethodGet,
				Path:    "/api/ai/inerview_app/chat/sse",
				Handler: ChatHandler(serverCtx),
			},
		},
	)
}
